### PR TITLE
Update lint group names

### PR DESCRIPTION
**Pull request by killercup**
Fixes usage on a nightly after https://github.com/rust-lang/rust/pull/50620

### CODE REVIEW

**Comment by killercup** [comment]
> Latest commit d9729ee  4 minutes ago
> @alexcrichton
> Fix CI for most recent nightly

-,..,-

**Comment by killercup** [comment]
Oh but actually no this PR is way better ;)

**Comment by alexcrichton** [comment]
Oops [pushed anyway](https://github.com/rust-lang-nursery/rustfix/commit/11ae16a54da3d01f4b9d1ad516214791206a6871)

(I should just always use PRs...)

**Comment by killercup** [comment]
No worries all that matters is that it works again :D

**Pull request closed without merging**
